### ISSUE TITLE
About the version of RLBench

### ISSUE THREAD

**Issue by weixiang-smart** [stepjam/ARM#10]
Hi. I think ARM is an excellent work for the intelligent robot. When I ran the code with the latest RLBench 1.1.0 release, I met some errors about RLBench.
```
Traceback (most recent call last):
  File "launch.py", line 17, in <module>
    from rlbench.action_modes.action_mode import MoveArmThenGripper
ModuleNotFoundError: No module named 'rlbench.action_modes.action_mode'; 'rlbench.action_modes' is not a package
```
It seems that the latest RLBench 1.1.0 release doesn't match the code. Can you help us with this situation? Thanks in advance.

**Comment by softgearko** [comment]
I'm using RLBench 1.2.  And I edited `RLBench/rlbench/action_modes/__init__.py`
```
from .action_mode import ActionMode
from .arm_action_modes import ArmActionMode
from .gripper_action_modes import GripperActionMode
```
Then, I reinstall rlbench. (` pip install . `)
After that, I launched C2FARM successfully.

**Comment by weixiang-smart** [comment]
> @weixiang-smart I used RLBench 1.2. And I edited `RLBench/rlbench/action_modes/__init__.py`
> 
> ```
> from .action_mode import ActionMode
> from .arm_action_modes import ArmActionMode
> from .gripper_action_modes import GripperActionMode
> ```
> 
> Then, I reinstall rlbench. (`pip install .`) After that, I launched C2FARM successfully.

Thank you so much! It works actually.
