### ISSUE TITLE
RuntimeError: Broken dataset assumption

### ISSUE THREAD

**Issue by RAFAY-AAMIR-GULL** [stepjam/ARM#12]
Hi,

I am having trouble in running this command:

python launch.py method=C2FARM rlbench.task=take_lid_off_saucepan rlbench.demo_path=/home/RLBench/tools/mnt/my/save/dir framework.gpu=0

And it shows me this:

/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
launch.py:330: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_name='config', config_path='conf')
/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'method/C2FARM': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
[2022-11-18 19:09:44,691][root][INFO] - 
method:
  name: C2FARM
  lr: 0.0005
  tau: 0.0025
  activation: lrelu
  norm: None
  lambda_weight_l2: 1.0e-06
  lambda_trans_qreg: 1.0
  lambda_rot_qreg: 1.0
  rotation_resolution: 5
  image_crop_size: 64
  bounds_offset:
  - 0.15
  voxel_sizes:
  - 16
  - 16
  crop_augmentation: true
  demo_augmentation: true
  demo_augmentation_every_n: 10
  exploration_strategy: gaussian
rlbench:
  task: take_lid_off_saucepan
  demos: 100
  demo_path: /home/itu/RL_FYP/RLBench/tools/mnt/my/save/dir
  episode_length: 100
  cameras:
  - front
  camera_resolution:
  - 128
  - 128
  scene_bounds:
  - -0.3
  - -0.5
  - 0.6
  - 0.7
  - 0.5
  - 1.6
replay:
  batch_size: 128
  timesteps: 1
  prioritisation: true
  use_disk: false
  path: /tmp/arm/replay
framework:
  log_freq: 100
  save_freq: 100
  train_envs: 1
  eval_envs: 1
  replay_ratio: 128
  transitions_before_train: 200
  tensorboard_logging: true
  csv_logging: true
  training_iterations: 40000
  gpu: 0
  env_gpu: 0
  logdir: /tmp/arm_test/
  seeds: 1

[2022-11-18 19:09:44,722][root][INFO] - Using training device cuda:0.
[2022-11-18 19:09:44,722][root][INFO] - Using env device cuda:0.
[2022-11-18 19:09:44,776][root][INFO] - CWD:/tmp/arm_test/take_lid_off_saucepan/C2FARM
[2022-11-18 19:09:44,777][root][INFO] - Starting seed 0.
[2022-11-18 19:09:44,777][root][INFO] - Creating a PrioritizedReplayBuffer replay memory with the following parameters:
[2022-11-18 19:09:44,778][root][INFO] - 	 timesteps: 1
[2022-11-18 19:09:44,778][root][INFO] - 	 replay_capacity: 100000
[2022-11-18 19:09:44,778][root][INFO] - 	 batch_size: 128
[2022-11-18 19:09:44,778][root][INFO] - 	 update_horizon: 1
[2022-11-18 19:09:44,778][root][INFO] - 	 gamma: 0.990000
[2022-11-18 19:09:44,778][root][INFO] - 	 saving to RAM
[2022-11-18 19:09:44,783][root][INFO] - Filling replay with demos...
Error executing job with overrides: ['method=C2FARM', 'rlbench.task=take_lid_off_saucepan', 'rlbench.demo_path=/home/itu/RL_FYP/RLBench/tools/mnt/my/save/dir', 'framework.gpu=0']
Traceback (most recent call last):
  File "launch.py", line 369, in main
    run_seed(cfg, env, cfg.rlbench.cameras, train_device, env_device, seed)
  File "launch.py", line 113, in run_seed
    cfg.method.rotation_resolution, cfg.method.crop_augmentation)
  File "/home/itu/RL_FYP/ARM/arm/c2farm/launch_utils.py", line 178, in fill_replay
    from_episode_number=d_idx)[0]
  File "/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/rlbench/environment.py", line 161, in get_demos
    task_name, self._obs_config, random_selection, from_episode_number)
  File "/home/itu/anaconda3/envs/env/lib/python3.6/site-packages/rlbench/utils.py", line 100, in get_stored_demos
    raise RuntimeError('Broken dataset assumption')
RuntimeError: Broken dataset assumption

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

We tried changing the path and other properties like episodes and length of episodes from config.yaml file, because we had 100  episodes in RLBench folder, but the same problem persists.

**Please help me out in getting this resolved.**

**Comment by Colin-KelinLi** [comment]
Same problem

**Comment by Colin-KelinLi** [comment]
Hi, I solved this problem by regenerating the demos to a new folder. Try this 

```
> python dataset_generator.py --save_path=/mnt/my/save/dir --tasks=take_lid_off_saucepan --image_size=128,128
> --renderer=opengl --episodes_per_task=100 --variations=1 --processes=1
```

**Comment by RAFAY-AAMIR-GULL** [comment]
Thanks, Colin,
The issue has been resolved.
