### ISSUE TITLE
about the version of trimesh

### ISSUE THREAD

**Issue by Xiangyu-Lee** [stepjam/ARM#18]
Hi, stepjam,
This is a good method. However, when I run laugh.py file, I get 'AttributeError: module 'trimesh' has no attribute 'voxel'' problem. Is this a problem with the trimesh version?

Best.

**Comment by lakshitadodeja** [comment]
Hey @xiangyu-Lee 
I am getting the same error. How did you fix it ?

**Comment by Xiangyu-Lee** [comment]
I'm sorry, I just saw it now. I changed the version of trimesh to 3.9.5, and it ran successfully.
