### ISSUE TITLE
question about calculate the attended coordinates in the demo trajectories

### ISSUE THREAD

**Issue by WeiChengTseng** [stepjam/ARM#3]
Hi,

Thanks for sharing this interesting project. However, I got confused about the voxel center calculation. 
However, it seems that the voxel center calculation is not consistent between demo data and policy inference (see the code below). 

https://github.com/stepjam/ARM/blob/c4285b6404702a97b3c5ac463af34c626f926b57/arm/c2farm/launch_utils.py#L96
https://github.com/stepjam/ARM/blob/c4285b6404702a97b3c5ac463af34c626f926b57/arm/c2farm/qattention_agent.py#L424

Just wondering whether it is a small bug or I misunderstand something.

Thanks a lot.

**Comment by stepjam** [comment]
Hi, thanks for your question! Yes that does seem to be a small bug, thanks for spotting!
Note that `res / 2` will be very small anyway, so adding in `res / 2` to line 96 should give similar results.

Cheers,
Stephen
