### ISSUE TITLE
Request for the source code of the real robot experiments

### ISSUE THREAD

**Issue by Marcelbgit** [stepjam/ARM#7]
Dear Stephen,

thank you for sharing your interesting work! I would like to use your concept to simulate my own use cases with a KUKA iiwa in my own environment and then test it in a real environment. So I would like to know how I can change the model and the environment in the simulation. Additionally, I would like to ask for the code for the real experiments so that I can adapt it for my use cases and test it with my real system. 

Thanks a lot for your help and best regards
Marcel

**Comment by stepjam** [comment]
Hi Marcel.
ARM is evaluated on RLBench, so you can swap the robot arm model using RLBench (https://github.com/stepjam/RLBench#swapping-arms)
We do not plan to release and maintain the real robot code because it specific to our real-world setup.

Cheers,
Stephen
